---
title: "Titanic"
author: "Sujit"
date: "May 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tree)
library(randomForest)
library(rpart)
library(adabag)
library(class)
library(BBmisc)
library(caret)
library(dplyr)
titanic_train_r<-read.csv("file:///C:/Users/Administrator/Downloads/train (1).csv")
titanic_test_r<-read.csv("file:///C:/Users/Administrator/Downloads/test.csv")
titanic_res<-read.csv("file:///C:/Users/Administrator/Downloads/gender_submission.csv")

```

```{r}

# Factor Columns
factor = colnames(titanic_train_r[,sapply(titanic_train_r, is.factor)])
factor

# Numerical Columns
numeric = colnames(titanic_train_r[,sapply(titanic_train_r, is.numeric)])
numeric = numeric[-1]
numeric


```



```{r}
rownames(which(cor(titanic_train_r[numeric])>0.5 & cor(titanic_train_r[numeric])!=1,arr.ind = T))

## Chi square test
a=sapply(titanic_train_r[factor], function(x){chisq.test(x,as.factor(titanic_train_r$Survived),simulate.p.value = T)$p.value})

b=which(a<0.05) 
# these are the columns that "default" column depends on


### Final factor columns
factor=factor[b]
factor


titanic_train_r=titanic_train_r[c(numeric,factor)]



str(titanic_train_r)

```






```{r}


titanic_train<-titanic_train_r %>% mutate(family_size=SibSp+Parch)%>% select(-c(SibSp,Parch))
titanic_train$Pclass<-as.factor(titanic_train$Pclass)
titanic_train<-titanic_train[c(-7,-6)]

titanic_test<-titanic_test_r %>% mutate(family_size=SibSp+Parch)%>% select(-c(SibSp,Parch))
titanic_test$Pclass<-as.factor(titanic_test$Pclass)

titanic_train$Survived<-as.factor(titanic_train$Survived)



colnames(titanic_test)


```

```{r}
str(titanic_test)

```




```{r}

titanic_train=titanic_train_r
model<-tree(Survived~.,data = titanic_train)
colSums(is.na(titanic_test))
b=titanic_norm1 %>% filter(Pclass==1,Parch==0)
titanic_test[153,"Fare"]=mean(b[,"Fare"],na.rm = T)
predicted<-predict(model,newdata = titanic_test)
predict<-ifelse(predicted[,1]>0.5,"0","1")


confusionMatrix(as.factor(titanic_res$Survived),as.factor(predict),positive = "1")

a=data.frame(PassengerId=titanic_test_r$PassengerId,Survived=predict)

write.csv(a,"survived.csv",row.names = F)

sum(predict==titanic_res$Survived)/(nrow(titanic_test))

a$table

```

```{r}
j=1
tpr=0
fpr=0
for (i in seq(0.05,0.9,0.05)) {
  predict<-ifelse(predicted[,1]>i,0,1)
  a=confusionMatrix(as.factor(titanic_res$Survived),as.factor(predict),positive = '1')
  tpr[j]=a$table[2,2]/(a$table[1,2]+a$table[2,2])
  fpr[j]=a$table[2,1]/(a$table[2,1]+a$table[1,1])
  j=j+1
}

plot(fpr,tpr,type = "l")

```





```{r}

model<-rpart(Survived~.,data = titanic_train)
predicted<-predict(model,titanic_test)

predicted<-predict(model,newdata = titanic_test)
predict<-ifelse(predicted[,1]>0.5,"0","1")

a=data.frame(PassengerId=titanic_test_r$PassengerId,Survived=predict)
write.csv(a,"survived.csv",row.names = F)

sum(titanic_res[,2]==predict)/nrow(titanic_test)



```

```{r}

model<-boosting(Survived~.,data = titanic_train,mfinal = 20)
predicted<-predict.boosting(model,titanic_test)

a=data.frame(PassengerId=titanic_test_r$PassengerId,Survived=predicted$class)
write.csv(a,"survived.csv",row.names = F)


sum(titanic_res[,2]==predicted$class)/nrow(titanic_test)


```

```{r}



dummy_obj = dummyVars(~., data=titanic_train %>% select(-Age))
titanic_new = data.frame(predict(dummy_obj, newdata = titanic_train %>% select(-Age)))

dummy_obj1 = dummyVars(~., data = titanic_test %>% select(-Age))
titanic_new1 = data.frame(predict(dummy_obj1,newdata = titanic_test %>% select(-Age)))
## Normalizing
titanic_norm = normalize(titanic_new, method='range', range = c(0,1))
titanic_norm1 = normalize(titanic_new1,method = 'range',range = c(0,1))

a=titanic_norm1 %>% filter(Pclass==1,Parch==0)
titanic_norm1[153,"Fare"]=mean(a[,"Fare"])

titanic_test$predict=knn(train = titanic_norm,test = titanic_norm1,cl = as.factor(titanic_norm$Survived),k = 5)

hr_test$Attrition = as.factor(hr_test$Attrition)
hr_test$predict = as.factor(hr_test$predict)
confusionMatrix(hr_test$predict, hr_test$Attrition, positive = '1')

View(titanic_norm1)

```



